<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Server status</title>
                <style>
                        body {
                                    font-family: Arial, sans-serif;
                                                background-color: #f7f7f7;
                                                        }
                                                                h3 {
                                                                            text-align: center;
                                                                                        color: #333;
                                                                                                }
                                                                                                        table {
                                                                                                                    width: 85%;
                                                                                                                                margin: 20px auto;
                                                                                                                                            border-collapse: collapse;
                                                                                                                                                        background-color: #fff;
                                                                                                                                                                    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                                                                                                                                                                            }
                                                                                                                                                                                    th, td {
                                                                                                                                                                                                border: 1px solid #ddd;
                                                                                                                                                                                                            padding: 12px;?
                                                                                                                                                                                                                        text-align: left;
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                        th {
                                                                                                                                                                                                                                                    background-color: #f2f2f2;
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                    font {
                                                                                                                                                                                                                                                                                color: #00C853;
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                .total-users {
                                                                                                                                                                                                                                                                                                            text-align: center;
                                                                                                                                                                                                                                                                                                                        margin-top: 20px;
                                                                                                                                                                                                                                                                                                                                    font-weight: bold;
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                                                                                                                </head>
                                                                                                                                                                                                                                                                                                                                                <body>
                                                                                                                                                                                                                                                                                                                                                    <h3>SVPN Server status</h3>
                                                                                                                                                                                                                                                                                                                                                        <?php
                                                                                                                                                                                                                                                                                                                                                            $servers = [
                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                             '🇹🇭 FREE 1' => 'http://tmvh.co.free1.sksfree.shop:81/server/online',
                                                                                                                                                                                                                                                                       '🇹🇭 FREE 2' => 'http://tmvh.co.free6.sksfree.shop:81/server/online',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '🇹🇭 FREE 3' => 'http://tmvh.co.free1new.sksfree.shop:81/server/online',
                                                                                                                                                                                                                                                                                                                                                                                            '🇹🇭 FREE 4' => 'http://tmvh.co.free4.sksfree.shop:81/server/online',
                                                                                          '🇹🇭 FREE 5' => 'http://tmvh.co.free5.sksfree.shop:81/server/online',                                              '🇹🇭 FREE 6' => 'http://tmvh.co.free2.sksfree.shop:81/server/online', 
                                                                                           '🇹🇭 FREE 7' => 'http://tmvh.co.free3.sksfree.shop:81/server/online',                                                                                            '🇹🇭 FREE 8' => 'http://tmvh.co.free8.sksfree.shop:81/server/online',                                                                              '🇹🇭 FREE 9' => 'http://tmvh.co.free9.sksfree.shop:81/server/online',                                                                                           
                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                                                    $totalOnlineCount = 0;

                                                                                                                                                                                                                                                                                                                                                                                                        echo '<table>';
                                                                                                                                                                                                                                                                                                                                                                                                            echo '<tr>
                                                                                                                                                                                                                                                                                                                                                                                                            <th>Server Name</th>
                                                                                                                                                                                                                                                                                                                                                                                                            <th>Status</th>
                                                                                                                                                                                                                                                                                                                                                                                                            </tr>';

                                                                                                                                                                                                                                                                                                                                                                                                                foreach ($servers as $serverName => $serverURL) {
                                                                                                                                                                                                                                                                                                                                                                                                                        $response = @file_get_contents($serverURL);

                                                                                                                                                                                                                                                                                                                                                                                                                                if ($response !== false) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            $onlineCount = intval($response);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "<tr><td>$serverName</td><td>Online <font color='#00C853'>$onlineCount</font> people</td></tr>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $totalOnlineCount += $onlineCount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $error = error_get_last();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "<tr><td>$serverName</td><td>Unable to connect to server - Error: " . $error['message'] . "</td></tr>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo '</table>';

                                                                                                                                                                                                                                                    // Check if it's taking too long to load. If so, refresh the page.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (connection_status() != CONNECTION_NORMAL) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    header("Refresh:0");
                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "<div class='total-users'>Total online users: <font color='#00C853'>$totalOnlineCount</font> people</div>";
                                                           ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>
